services:
  backend:
    build:
      target: production
    volumes: [] # Production doesn't need host volumes
    environment:
      - NODE_ENV=production

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
     # Or more secure:
     # - "127.0.0.1:3000:3000"
     
  # frontend:
  #   build:
  #     target: production
  #   volumes: []
  #   ports:
  #     - "5173:80" # Map host 5173 to Nginx port 80
  #   environment:
  #     - NODE_ENV=production
